{% set name = "perses" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/choderalab/perses/archive/{{ version }}.tar.gz
  sha256: 5a2f425ed72007119280308ab73b52d84d3f02588ae89f89f08e5d59b5ca66a6

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  entry_points:
    - perses-relative = perses.app.setup_relative_calculation:run
    - perses-fah = perses.app.fah_generator:run

requirements:
  host:
    - python >=3.6
    - pip
    - numpy
  run:
    - python >=3.6
    - numpy
    - scipy
    - numba
    - netcdf4
    - matplotlib-base
    - seaborn
    - networkx >=2.0
    - dask
    - distributed
    - tqdm
    - pyyaml
    - pandas
    - dask-jobqueue
    - dicttoxml
    - fire
    - joblib
    - mdtraj
    - pymbar >=3.0.6,<4
    - ambertools >=19.11
    - openmm >=7.6
    - openmmforcefields
    - openmoltools >=0.8.4
    - openmmtools >=0.21.2
    - openff-toolkit >=0.9.0,<0.11
    - click
    - arsenic
    - cloudpathlib
    # - openeye-toolkits

test:
  imports:
    - perses
  # commands:
    # # these require openeye toolkits
    # - perses-relative --help
    # - perses-fah --help

about:
  home: https://github.com/choderalab/perses
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Experiments with expanded ensemble simulation to explore chemical and mutational space
  description: |
    Experiments with expanded ensemble simulation to explore chemical and mutational space
  doc_url: http://perses.readthedocs.io/
  dev_url: https://github.com/choderalab/perses

extra:
  recipe-maintainers:
    - jaimergp
    - jchodera
    - mikemhenry
    - ijpulidos
